version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 # 14 is not supported as of yet
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      # creating a permanent folder
      - echo "Making a temp directory"
      - mkdir /tmp/build
      # copying services content to the folder
      - mv services /tmp/build/
      - cd /tmp/build
      # - sam --version
      - cd services/user-service
      - echo "Current working dir is $(pwd)"

  pre_build:
    commands:
      - cd users-lambda
      # Installing project dependencies
      - npm install
      # Run tests, lint scripts or any other pre-build checks.
      - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
      - sam build --debug

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - sam package --s3-bucket $PACKAGE_BUCKET --s3-prefix 'user-service' --output-template-file packaged.yaml --debug
      - aws s3 cp packaged.yaml s3://$PACKAGE_BUCKET/user-service/

# artifacts:
#   discard-paths: yes
#   files:
#     # List of local artifacts that will be passed down the pipeline
#     - /tmp/build/services/user-service/packaged.yaml