version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 # 14 is not supported as of yet
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      # - sam --version
      # Installing project dependencies
      - cd services/user-service

  
  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.
      - cd users-lambda
      - npm install
      - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
      - sam build --debug

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - sam package --s3-bucket $PACKAGE_BUCKET --s3-prefix 'user-service' --output-template-file packaged.yaml --debug

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - services/user-service/packaged.yaml